import './style.css';
import './menu.css';
import './shop.css';
import { carpets, tools, toolOrder } from './data/game.js';
import { initYandex, gameReady, gameplayStart, gameplayStop } from './platform/yandex.js';
import { initI18n, setLocale, getLocale, t } from './i18n/index.js';
import { CleaningController } from './cleaning/CleaningController.js';
import { renderShop, bindShop } from './shop.js';
const app=document.querySelector('#app');
let index=0,controller=null,selectedTool='brush',currentScreen='menu',paused=false;
let soundEnabled=localStorage.getItem('rugrestorer.sound')!=='off';
const carpetKey=c=>c.id==='classic'?'persian':c.id;
const gradeKey=g=>({S:'master',A:'expert',B:'great',C:'good',D:'rough'})[g.short];
const toolText=id=>({brush:'balanced',scrubber:'powerful',detail:'precise'})[id];
function languageButtons(){return `<div class="language-switch"><span>${t('language')}</span><button class="lang ${getLocale()==='ru'?'active':''}" data-lang="ru">RU</button><button class="lang ${getLocale()==='en'?'active':''}" data-lang="en">EN</button></div>`}
function bindLanguage(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{setLocale(b.dataset.lang);renderCurrentScreen()})}
function cleanupGame(){if(controller){controller.destroy();controller=null}paused=false;gameplayStop()}
function menu(){cleanupGame();currentScreen='menu';app.innerHTML=`<main class="screen menu workshop-menu"><div class="workshop-backdrop"><div class="wall-clock">10:24</div><div class="shelf"><i></i><i></i><i></i></div><div class="hanging-lamp"></div><div class="wall-frame"><span></span></div><div class="window-light"></div></div><div class="menu-scene"><div class="dust-layer"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="scene-title"><div class="brand"><span>RUG</span> RESTORER</div><p>${t('tagline')}</p></div><div class="master-area"><div class="rug-rack"><b></b><b></b><b></b><span></span></div><div class="plant"><i></i><i></i><i></i><b></b></div><div class="master-silhouette"><div class="master-head"></div><div class="master-body"></div><div class="master-arm"></div></div><div class="workbench"><div class="bench-top"></div><div class="bench-front"></div><div class="bench-leg left"></div><div class="bench-leg right"></div><div class="bench-rug"><span></span><b></b></div><div class="bench-tools"><i>🧹</i><i>🧽</i><i>🪥</i></div><div class="lamp-small"></div></div></div><div class="menu-panel"><div class="panel-label">${t('workshop')}</div><div class="menu-actions"><button id="start">${t('start')}</button><button class="secondary" id="shop">${t('shop')}</button><button class="secondary" id="profile">${t('profile')}</button><button class="secondary" id="settings">${t('settings')}</button></div></div><div class="menu-footer">${languageButtons()}<small>${t('version')}</small></div></div></main>`;document.querySelector('#start').onclick=start;document.querySelector('#shop').onclick=shopScreen;document.querySelector('#profile').onclick=()=>infoScreen('profile');document.querySelector('#settings').onclick=settings;bindLanguage()}
function shopScreen(){currentScreen='shop';app.innerHTML=renderShop(t);bindShop(t,menu)}
function infoScreen(type){currentScreen=type;app.innerHTML=`<main class="screen sub-screen"><div class="panel"><div class="panel-icon">◇</div><h1>${t(type)}</h1><p>${t(type+'Soon')}</p><button id="back">${t('backMenu')}</button></div>${languageButtons()}</main>`;document.querySelector('#back').onclick=menu;bindLanguage()}
function settings(){currentScreen='settings';app.innerHTML=`<main class="screen sub-screen"><div class="panel settings-panel"><h1>${t('settingsTitle')}</h1><div class="setting-row"><span>${t('sound')}</span><button id="sound" class="toggle ${soundEnabled?'on':''}">${soundEnabled?t('soundOn'):t('soundOff')}</button></div><div class="setting-row"><span>${t('language')}</span><div class="inline-lang"><button class="lang ${getLocale()==='ru'?'active':''}" data-lang="ru">RU</button><button class="lang ${getLocale()==='en'?'active':''}" data-lang="en">EN</button></div></div><button id="close">${t('close')}</button></div>${languageButtons()}</main>`;document.querySelector('#sound').onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem('rugrestorer.sound',soundEnabled?'on':'off');settings()};document.querySelector('#close').onclick=menu;bindLanguage()}
function start(){cleanupGame();currentScreen='game';paused=false;gameplayStart();const carpet=carpets[index],tool=tools[selectedTool],rugNumber=String(index+1).padStart(3,'0');app.innerHTML=`<main class="screen game"><header><div><b>${t('rug',{id:rugNumber})}</b><span>${t(carpetKey(carpet))}</span></div><div class="score"><strong id="quality">100</strong><small>${t('quality')}</small></div><strong id="progress">0%</strong><button class="game-menu-button" id="game-menu">☰</button></header><section class="work"><div class="hint" id="hint">${t('chooseTool')}</div><canvas id="rug"></canvas><div class="brush"><img id="tool-image" src="${tool.asset}" alt=""><span id="tool-label">${t(tool.id)}</span></div><div class="toolbelt">${toolOrder.map(id=>{const x=tools[id];return `<button class="tool ${id===selectedTool?'active':''}" data-tool="${id}" title="${t(toolText(id))}"><img src="${x.asset}" alt=""><span>${t(id)}</span></button>`}).join('')}</div></section><div class="bar"><i id="bar"></i></div><div class="metrics"><span id="grade">${t('rough')}</span><span id="strokes">${t('strokes',{value:0})}</span><span id="distance">${t('distance',{value:0})}</span></div><div id="pause-layer" class="pause-layer hidden"></div></main>`;const update=s=>{const progress=document.querySelector('#progress');if(!progress)return;progress.textContent=`${s.progress}%`;document.querySelector('#quality').textContent=s.quality;document.querySelector('#grade').textContent=t(gradeKey(s.grade));document.querySelector('#strokes').textContent=t('strokes',{value:s.stats.strokes});document.querySelector('#distance').textContent=t('distance',{value:Math.round(s.stats.distance)});document.querySelector('#bar').style.width=`${s.progress}%`;document.querySelector('#tool-label').textContent=t(s.tool.id);document.querySelector('#tool-image').src=s.tool.asset};controller=new CleaningController(document.querySelector('#rug'),carpet,tool,update,{soundEnabled});document.querySelectorAll('.tool').forEach(button=>button.onclick=()=>{if(paused)return;selectedTool=button.dataset.tool;controller.setTool(tools[selectedTool]);document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===button));document.querySelector('#hint').textContent=t(toolText(selectedTool));update({progress:controller.progress(),quality:controller.quality(),grade:controller.grade(),tool:controller.tool,stats:controller.stats})});document.querySelector('#game-menu').onclick=()=>togglePause(true);let completed=false;const tick=()=>{if(controller&&!paused&&controller.progress()>=100&&!completed){completed=true;gameplayStop();setTimeout(()=>result(controller),500);return}if(currentScreen==='game')requestAnimationFrame(tick)};tick()}
function pauseMarkup(){return `<div class="pause-card"><div class="pause-mark">Ⅱ</div><h1>${t('pause')}</h1><button id="resume">${t('resume')}</button><button class="secondary" id="pause-settings">${t('settings')}</button><button class="secondary" id="pause-menu">${t('backMenu')}</button>${languageButtons()}</div>`}
function togglePause(value=!paused){if(currentScreen!=='game'||!controller)return;paused=value;controller.setPaused(paused);const layer=document.querySelector('#pause-layer');if(!layer)return;layer.classList.toggle('hidden',!paused);if(paused){layer.innerHTML=pauseMarkup();document.querySelector('#resume').onclick=()=>togglePause(false);document.querySelector('#pause-settings').onclick=settingsFromPause;document.querySelector('#pause-menu').onclick=menu}}
function settingsFromPause(){if(!controller)return;const layer=document.querySelector('#pause-layer');layer.innerHTML=`<div class="pause-card"><div class="pause-mark">⚙</div><h1>${t('settingsTitle')}</h1><div class="setting-row"><span>${t('sound')}</span><button id="pause-sound" class="toggle ${soundEnabled?'on':''}">${soundEnabled?t('soundOn'):t('soundOff')}</button></div><div class="setting-row"><span>${t('language')}</span><div class="inline-lang"><button class="lang ${getLocale()==='ru'?'active':''}" data-lang="ru">RU</button><button class="lang ${getLocale()==='en'?'active':''}" data-lang="en">EN</button></div></div><button id="settings-back">${t('close')}</button></div>`;document.querySelector('#pause-sound').onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem('rugrestorer.sound',soundEnabled?'on':'off');controller.setSoundEnabled(soundEnabled);settingsFromPause()};document.querySelector('#settings-back').onclick=()=>{layer.innerHTML=pauseMarkup();document.querySelector('#resume').onclick=()=>togglePause(false);document.querySelector('#pause-settings').onclick=settingsFromPause;document.querySelector('#pause-menu').onclick=menu}}
function result(job){currentScreen='result';const grade=job.grade(),quality=job.quality(),stars='★★★★★'.slice(0,grade.stars)+'☆☆☆☆☆'.slice(0,5-grade.stars),nextLabel=index<carpets.length-1?t('next'):t('back'),resultText=quality>=95?'flawless':quality>=88?'excellent':quality>=76?'solid':'roughResult';app.innerHTML=`<main class="screen result"><div class="check">✓</div><div class="grade-rank">${grade.short}</div><h1>${t(gradeKey(grade))}</h1><div class="stars">${stars}</div><div class="final-score"><b>${quality}</b><span>${t('qualityScore')}</span></div><div class="result-stats"><span>${t('strokes',{value:''})}<b>${job.stats.strokes}</b></span><span>${t('distance',{value:''})}<b>${Math.round(job.stats.distance)}</b></span><span>${t('tool')}<b>${t(job.tool.id)}</b></span></div><p>${t(resultText)}</p><button id="next">${nextLabel}</button>${languageButtons()}</main>`;document.querySelector('#next').onclick=()=>{if(index<carpets.length-1){index++;start()}else{index=0;menu()}};bindLanguage()}
function renderCurrentScreen(){if(currentScreen==='result'&&controller){result(controller);return}if(currentScreen==='menu'){menu();return}if(currentScreen==='settings'){settings();return}if(currentScreen==='shop'){shopScreen();return}if(currentScreen==='profile'){infoScreen('profile');return}if(currentScreen==='game'&&paused)togglePause(true)}
function handleVisibility(){if(currentScreen==='game'&&controller&&document.hidden)togglePause(true)}
document.addEventListener('visibilitychange',handleVisibility);window.addEventListener('blur',()=>{if(currentScreen==='game'&&controller)togglePause(true)});
async function boot(){const platform=await initYandex();initI18n(platform.lang||(navigator.language||'en').slice(0,2).toLowerCase());menu();gameReady()}boot();