export class CleaningController {
 constructor(canvas,carpet,tool,onStats=()=>{},options={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.carpet=carpet;this.tool=tool;this.onStats=onStats;this.soundEnabled=options.soundEnabled!==false;this.onCleanerUse=options.onCleanerUse||null;this.dirtIntensity=options.dirtIntensity??1;this.stains=options.stains??8;this.stainTypes=options.stainTypes||['dust'];this.variation=options.variation??0;this.requiresCleaner=Boolean(options.requiresCleaner);this.paused=false;this.active=false;this.last=null;this.particles=[];this.dirtyCanvas=document.createElement('canvas');this.dirtyCtx=this.dirtyCanvas.getContext('2d');this.treatedCanvas=document.createElement('canvas');this.treatedCtx=this.treatedCanvas.getContext('2d');this.progressCanvas=document.createElement('canvas');this.progressCanvas.width=128;this.progressCanvas.height=128;this.progressCtx=this.progressCanvas.getContext('2d',{willReadFrequently:true});this.audio=null;this.ready=false;this.lastFrame=performance.now();this.cleanerApplied=false;this.stats={strokes:0,distance:0,wasted:0,toolUses:{},cleanerUses:0,cleanerDistance:0};this.resizeHandler=()=>this.resize();this.resize();this.bind();this.animate=this.animate.bind(this);requestAnimationFrame(this.animate);this.loadAssets()}
 async loadAssets(){const[rug,dirt]=await Promise.all([this.loadImage(this.carpet.asset),this.loadImage(this.carpet.dirtMask)]);this.rugImage=rug;this.dirtImage=dirt;this.dirtyCanvas.width=Math.max(1,Math.round(this.w));this.dirtyCanvas.height=Math.max(1,Math.round(this.h));this.treatedCanvas.width=this.dirtyCanvas.width;this.treatedCanvas.height=this.dirtyCanvas.height;this.drawDirtImage();this.initialDirty=this.measureDirty();this.dirty=this.initialDirty;this.ready=true;this.emitStats();this.draw()}
 loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
 resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.canvas.width=Math.max(1,Math.round(this.w*d));this.canvas.height=Math.max(1,Math.round(this.h*d));this.ctx.setTransform(d,0,0,d,0,0);if(this.dirtyCanvas.width&&this.dirtyCanvas.height&&this.ready){const old=document.createElement('canvas');old.width=this.dirtyCanvas.width;old.height=this.dirtyCanvas.height;old.getContext('2d').drawImage(this.dirtyCanvas,0,0);this.dirtyCanvas.width=Math.max(1,Math.round(this.w));this.dirtyCanvas.height=Math.max(1,Math.round(this.h));this.dirtyCtx.drawImage(old,0,0,old.width,old.height,0,0,this.w,this.h);const treated=document.createElement('canvas');treated.width=this.treatedCanvas.width;treated.height=this.treatedCanvas.height;treated.getContext('2d').drawImage(this.treatedCanvas,0,0);this.treatedCanvas.width=this.dirtyCanvas.width;this.treatedCanvas.height=this.dirtyCanvas.height;this.treatedCtx.drawImage(treated,0,0,treated.width,treated.height,0,0,this.w,this.h)}else{this.dirtyCanvas.width=Math.max(1,Math.round(this.w));this.dirtyCanvas.height=Math.max(1,Math.round(this.h));this.treatedCanvas.width=this.dirtyCanvas.width;this.treatedCanvas.height=this.dirtyCanvas.height}this.draw()}
 bind(){this.canvas.onpointerdown=e=>{if(this.paused)return;this.active=true;this.canvas.setPointerCapture(e.pointerId);this.initAudio();this.stats.strokes++;this.stats.toolUses[this.tool.id]=(this.stats.toolUses[this.tool.id]||0)+1;this.paint(e)};this.canvas.onpointermove=e=>{if(this.active&&!this.paused)this.paint(e)};this.canvas.onpointerup=()=>{this.active=false;this.last=null};this.canvas.onpointercancel=()=>{this.active=false;this.last=null};window.addEventListener('resize',this.resizeHandler)}
 destroy(){window.removeEventListener('resize',this.resizeHandler);this.canvas.onpointerdown=null;this.canvas.onpointermove=null;this.canvas.onpointerup=null;this.canvas.onpointercancel=null;if(this.audio){this.audio.close();this.audio=null}}
 setTool(tool){this.tool=tool;this.last=null}
 setSoundEnabled(enabled){this.soundEnabled=Boolean(enabled)}
 setPaused(paused){this.paused=Boolean(paused);this.active=false;this.last=null;if(!this.paused&&this.audio?.state==='suspended')this.audio.resume();this.emitStats()}
 initAudio(){if(!this.soundEnabled||this.audio)return;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;this.audio=new AudioCtx();if(this.audio.state==='suspended')this.audio.resume()}
 brushSound(intensity=.05){if(!this.soundEnabled||!this.audio)return;const now=this.audio.currentTime,osc=this.audio.createOscillator(),gain=this.audio.createGain(),filter=this.audio.createBiquadFilter();osc.type='triangle';osc.frequency.setValueAtTime(90+Math.random()*55,now);osc.frequency.exponentialRampToValueAtTime(65,now+.055);filter.type='lowpass';filter.frequency.value=950;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(intensity,now+.008);gain.gain.exponentialRampToValueAtTime(.0001,now+.065);osc.connect(filter).connect(gain).connect(this.audio.destination);osc.start(now);osc.stop(now+.07)}
 paint(e){if(!this.ready||this.paused)return;const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,dx=x-this.w/2,dy=y-this.h/2,rw=this.w*.39,rh=Math.min(this.h*.34,rw/this.carpet.ratio);if(Math.abs(dx)>rw||Math.abs(dy)>rh)return;const distance=this.last?Math.hypot(x-this.last.x,y-this.last.y):0,steps=Math.max(1,Math.ceil(distance/Math.max(6,this.tool.radius*.3)));if(this.tool.id==='cleaner'){if(!this.cleanerApplied&&this.onCleanerUse&&!this.onCleanerUse())return;this.treatLine(x,y,steps);this.last={x,y};this.stats.cleanerDistance+=distance;this.stats.cleanerUses=1;this.cleanerApplied=true;this.brushSound(.025);this.emitStats();return}if(this.requiresCleaner&&!this.cleanerApplied){this.last={x,y};this.stats.wasted+=1;this.emitStats();return}const previous=this.dirty;for(let i=1;i<=steps;i++){const tt=i/steps,px=this.last?this.last.x+(x-this.last.x)*tt:x,py=this.last?this.last.y+(y-this.last.y)*tt:y;if(this.isTreatedAt(px,py))this.erase(px,py);if(Math.random()<.5*this.tool.coverage)this.spawnDust(px,py)}this.last={x,y};this.stats.distance+=distance;this.dirty=this.measureDirty();const removed=Math.max(0,previous-this.dirty);const screenScale=Math.max(1,Math.min(this.w,this.h)/128);const expected=Math.PI*(this.tool.radius*.78)**2*steps*this.tool.power/(screenScale*screenScale);const efficiency=Math.min(1,removed/Math.max(1,expected));this.stats.wasted+=Math.max(0,1-efficiency);this.brushSound(Math.min(.07,.022+distance*.0009)*this.tool.coverage);this.emitStats()}
 treatLine(x,y,steps){const radius=Math.max(24,this.tool.radius*.8),c=this.treatedCtx;for(let i=1;i<=steps;i++){const tt=i/steps,px=this.last?this.last.x+(x-this.last.x)*tt:x,py=this.last?this.last.y+(y-this.last.y)*tt:y;c.save();c.globalCompositeOperation='source-over';c.fillStyle='rgba(90,190,255,.32)';c.beginPath();c.arc(px,py,radius,0,Math.PI*2);c.fill()}}
 applyCleaner(){if(!this.requiresCleaner||!this.ready)return false;this.cleanerApplied=true;this.stats.cleanerUses=Math.max(1,this.stats.cleanerUses);this.emitStats();this.draw();return true}
 hasCleanerApplied(){return !this.requiresCleaner||this.cleanerApplied}
 isTreatedAt(x,y){if(!this.requiresCleaner)return true;const px=Math.max(0,Math.min(this.treatedCanvas.width-1,Math.round(x))),py=Math.max(0,Math.min(this.treatedCanvas.height-1,Math.round(y)));return this.treatedCtx.getImageData(px,py,1,1).data[3]>15}
 erase(x,y){const c=this.dirtyCtx;c.save();c.globalCompositeOperation='destination-out';c.beginPath();c.arc(x,y,this.tool.radius*.78*this.tool.precision,0,Math.PI*2);c.fill();c.restore()}
 spawnDust(x,y){for(let i=0;i<Math.max(1,Math.round(2*this.tool.coverage));i++)this.particles.push({x,y,vx:(Math.random()-.5)*36,vy:-18-Math.random()*38,life:.32+Math.random()*.28,size:1.5+Math.random()*3})}
 updateParticles(dt){if(this.paused)return;for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=48*dt;p.life-=dt}this.particles=this.particles.filter(p=>p.life>0)}
 measureDirty(){if(!this.dirtImage||!this.w||!this.h)return 0;const c=this.progressCtx;c.clearRect(0,0,128,128);c.drawImage(this.dirtyCanvas,0,0,128,128);const data=c.getImageData(0,0,128,128).data;let alpha=0;for(let i=3;i<data.length;i+=4)alpha+=data[i];return alpha}
 progress(){if(!this.initialDirty)return 0;return Math.min(100,Math.max(0,Math.round((1-this.dirty/this.initialDirty)*100)))}
 quality(){const clean=this.progress();if(!this.ready||clean<100)return Math.round(clean*.7);const strokesPenalty=Math.min(18,Math.max(0,this.stats.strokes-8)*1.15);const normalizedDistance=this.stats.distance/(Math.max(1,Math.min(this.w,this.h))*2);const distancePenalty=Math.min(14,Math.max(0,normalizedDistance-5)*1.8);const wastePenalty=Math.min(24,this.stats.wasted/Math.max(1,this.stats.distance/(Math.max(1,this.tool.radius)))*18);const toolPenalty=this.tool.id===this.carpet.idealTool?0:7;return Math.max(0,Math.min(100,Math.round(100-strokesPenalty-distancePenalty-wastePenalty-toolPenalty)))}
 grade(){const q=this.quality();if(q>=95)return{label:'MASTER RESTORATION',short:'S',stars:5};if(q>=88)return{label:'EXPERT CLEAN',short:'A',stars:4};if(q>=76)return{label:'GREAT JOB',short:'B',stars:3};if(q>=62)return{label:'GOOD CLEAN',short:'C',stars:2};return{label:'ROUGH CLEAN',short:'D',stars:1}}
 emitStats(){this.onStats({progress:this.progress(),quality:this.quality(),grade:this.grade(),tool:this.tool,paused:this.paused,stats:{...this.stats},cleanerApplied:this.cleanerApplied,requiresCleaner:this.requiresCleaner})}
 drawDirtImage(){const c=this.dirtyCtx;c.clearRect(0,0,this.w,this.h);const rw=this.w*.39,rh=Math.min(this.h*.34,rw/this.carpet.ratio);c.save();c.translate(this.w/2,this.h/2);c.globalAlpha=this.dirtIntensity;c.beginPath();if(this.carpet.shape==='oval')c.ellipse(0,0,rw,rh,0,0,Math.PI*2);else c.roundRect(-rw,-rh,rw*2,rh*2,Math.min(28,rw*.08));c.clip();c.drawImage(this.dirtImage,-rw,-rh,rw*2,rh*2);this.drawStains(c,rw,rh);c.restore()}
 drawStains(c,rw,rh){let seed=this.variation||1;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let i=0;i<this.stains;i++){const x=(rand()-.5)*rw*1.7,y=(rand()-.5)*rh*1.7,size=(.015+rand()*.08)*Math.min(rw,rh),type=this.stainTypes[Math.floor(rand()*this.stainTypes.length)];c.save();c.globalCompositeOperation='source-over';c.globalAlpha=this.dirtIntensity*(type==='deep'?.72:type==='grease'?.55:.38);c.fillStyle=type==='grease'?'#6b4932':type==='mud'?'#80624b':type==='deep'?'#49382e':type==='spots'?'#9b7659':'#705b49';c.beginPath();c.ellipse(x,y,size*(.7+rand()*.8),size*(.35+rand()*1.1),rand()*Math.PI,0,Math.PI*2);c.fill();c.restore()}}
 animate(now){const dt=Math.min(.035,(now-this.lastFrame)/1000||.016);this.lastFrame=now;this.updateParticles(dt);this.draw();requestAnimationFrame(this.animate)}
 draw(){if(!this.w||!this.h)return;const c=this.ctx;c.clearRect(0,0,this.w,this.h);const cx=this.w/2,cy=this.h/2,rw=this.w*.39,rh=Math.min(this.h*.34,rw/this.carpet.ratio);c.save();c.translate(cx,cy);c.beginPath();if(this.carpet.shape==='oval')c.ellipse(0,0,rw,rh,0,0,Math.PI*2);else c.roundRect(-rw,-rh,rw*2,rh*2,Math.min(28,rw*.08));c.clip();if(this.rugImage)c.drawImage(this.rugImage,-rw,-rh,rw*2,rh*2);c.restore();if(this.ready)c.drawImage(this.dirtyCanvas,0,0,this.w,this.h);if(this.requiresCleaner){c.save();c.globalAlpha=.7;c.drawImage(this.treatedCanvas,0,0,this.w,this.h);c.restore()}for(const p of this.particles){c.globalAlpha=Math.max(0,p.life/.6);c.fillStyle='#d4b994';c.beginPath();c.arc(p.x,p.y,p.size,0,Math.PI*2);c.fill()}c.globalAlpha=1;if(this.active&&this.last&&!this.paused){c.strokeStyle='rgba(255,255,255,.9)';c.lineWidth=2;c.beginPath();c.arc(this.last.x,this.last.y,this.tool.radius,0,Math.PI*2);c.stroke()}}
}
